### PR TITLE
made changes to support py3

### PR DESCRIPTION
**Pull request by vhawk19**

### CODE REVIEW

**Comment by de-sh** [comment]
Did you run a PEP8 conformance test?

Use [pycodestyle.pycqa.org](http://pycodestyle.pycqa.org)

**Comment by subins2000** [comment]
@de-sh yeah, there was a PEP-8 error with `print` :

It should be `print()` and not `print ()`

**Comment by vhawk19** [comment]
I thought @subin did that, thats why didnt run the PEP8 conformance test.

**Comment by subins2000** [comment]
Which editor are you using ? There's probably a PEP-8 checking addon available

and my tag is @subins2000 . Don't mistake the tag !

**Comment by de-sh** [comment]
@subins2000, just use pycodestyles like a CLI ninja 😜

**Comment by vhawk19** [comment]
Sorry for the confusion!
And yes wont forget your tag @subins2000
Added PEP8 checking plugin!
Thanks.

**Pull request merged**
